### ISSUE TITLE
[Feature Request] Can not tag the url?

### ISSUE THREAD

**Issue by zhouyijiaren** [OlegWock/raindrop-telegram-bot#3]
The bot can't add tags to the favorite URL?

**Comment by OlegWock** [comment]
@zhouyijiaren could you elaborate what you mean? Currently bot just saves link to 'Unsorted' folder, it doesn't add any tags (and there is no functionality to do so at the moment)

**Comment by zhouyijiaren** [comment]
OK, I understand. 
I have made a TelegramBot myself to solve this kind of request.
